language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler --version 1.17.2
script:
- npm install alex@8.0.1 markdownlint-cli@0.19.0 --global
- bash scripts/language-check.sh
- bash scripts/markdown-lint.sh
- bundle exec middleman build
