language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
script:
- npm install alex markdownlint-cli --global
- bash scripts/language-check.sh
- bash scripts/markdown-lint.sh
- bundle exec middleman build
